# Generated by Django 3.2.6 on 2021-08-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, default=0, null=True, verbose_name='duration')),
                ('capture1', models.TextField(blank=True)),
                ('capture2', models.TextField(blank=True)),
                ('capture3', models.TextField(blank=True)),
                ('capture4', models.TextField(blank=True)),
                ('capture5', models.TextField(blank=True)),
                ('capture6', models.TextField(blank=True)),
                ('capture7', models.TextField(blank=True)),
                ('capture8', models.TextField(blank=True)),
                ('capture9', models.TextField(blank=True)),
                ('capture10', models.TextField(blank=True)),
                ('capture11', models.TextField(blank=True)),
                ('capture12', models.TextField(blank=True)),
                ('capture13', models.TextField(blank=True)),
                ('capture14', models.TextField(blank=True)),
                ('capture15', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='DramaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, default=0, null=True, verbose_name='duration')),
                ('season', models.IntegerField(blank=True, default=0, null=True, verbose_name='season')),
                ('episode', models.IntegerField(blank=True, default=0, null=True, verbose_name='episode')),
                ('capture1', models.TextField(blank=True)),
                ('capture2', models.TextField(blank=True)),
                ('capture3', models.TextField(blank=True)),
                ('capture4', models.TextField(blank=True)),
                ('capture5', models.TextField(blank=True)),
                ('capture6', models.TextField(blank=True)),
                ('capture7', models.TextField(blank=True)),
                ('capture8', models.TextField(blank=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dramaContent', to='api.drama')),
            ],
        ),
    ]
