# Generated by Django 3.2.6 on 2022-03-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_key', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
            ],
        ),
    ]
