# Generated by Django 3.2.6 on 2022-03-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='word',
            old_name='list_key',
            new_name='list_id',
        ),
        migrations.AddField(
            model_name='word',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.youtubemovie'),
        ),
    ]
