# Generated by Django 3.2.6 on 2022-03-07 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220307_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dramacontent',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture10',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture11',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture12',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture13',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture14',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture15',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture4',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture5',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture6',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture7',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture8',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='capture9',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated',
        ),
        migrations.AddField(
            model_name='movie',
            name='v',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Drama',
        ),
        migrations.DeleteModel(
            name='DramaContent',
        ),
        migrations.DeleteModel(
            name='YoutubeMovie',
        ),
    ]
