# Generated by Django 3.2.6 on 2022-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='displayName',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
