# Generated by Django 3.2.6 on 2022-05-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usermodel_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='v',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='list_id',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='word',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
