# Generated by Django 3.2.6 on 2022-03-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220309_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
