# Generated by Django 3.2.6 on 2022-03-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
